config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get '/about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :totos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toto.rb
class Toto < ApplicationRecord
  validates :name,presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/totos_controller.rb
class TotosController < ApplicationController

  before_action :set_toto, only: [:edit, :show, :update, :destroy]

  def new
    @toto = Toto.new
  end

  def create
    @toto = Toto.new(toto_params)
    if @toto.save
      flash[:notice] = "Todo is created successfully"
      redirect_to toto_path(@toto)
    else
      render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update

    if @toto.update(toto_params)
      flash[:notice] = "Toto was successfully updated"
       redirect_to toto_path(@toto)
    else
      render 'edit'
    end
  end

  def index
    @totos = Toto.all
  end

  def destroy

    @toto.destroy
    flash[:notice] = "Toto was deleted successfully"
    redirect_to totos_path
  end
  private
  def toto_params
    params.require(:toto).permit(:name, :description)
  end

  def set_toto
    @toto = Toto.find(params[:id])
  end
end
=begin
def create
  @toto = Toto.create(totos_params)
  if @toto.save
    flash[:notice] = "Toto is created successfully"
    redirect_to toto_path(@toto)
  else
    render 'new'
  end
end

def show
  @toto = Toto.find(params[:id])
end

private
def totos_params
  params.require(:toto).permit(:name, :description)
end
=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Totoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>-----------------------------------<h1>

app/views/pages/home.html.erb
<h1 style="color:green;">Hello World</h1><br><br>
<p style ="color : cyan;font-size : 34px"> Welcome to Ruby on Rails </p>

app/views/totos/_form.html.erb
<% if @toto.errors.any? %>
  <h3>The following errors prevents the toto from beign saved</h3>
  <ul>
    <% @toto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @toto do |t| %>
<div style = "margin-left:35%;">
  <table>
      <tr>
        <td>
            <label>Name</label></td>
            <td><%= t.text_field :name %>
        </td>
      </tr>
      <tr>
        <td>
            <%= t.label :descs %></td>

            <td><%= t.text_area :description %>
        </td>
      </tr>
      <tr>
        <td align="center">
          <%= t.submit %>
        </td>
      </tr>
  </table>
  <p>
    <%= link_to "Back to listings", totos_path%>
  </p>
</div>
<% end %>

app/views/totos/edit.html.erb
<h1>Edit an existing Todo</h1>

<%= render 'form' %>

app/views/totos/index.html.erb
<h1>Listing all Totos</h1>
<p>
<%= link_to "Create Totos",new_toto_path %>
</p>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @totos.each  do |t| %>
    <tr>
      <td ><%= t.id %></td>
      <td ><%= t.name %></td>
      <td ><%= t.description %></td>
      <td><%= link_to "Edit", edit_toto_path(t)%></td> 
      <td><%= link_to "Show", toto_path(t)%></td>
      <td><%= link_to "Delete", toto_path(t), method: :delete, data: {confirm: "Are you sure ?"}%></td>
    </tr>
  <% end %>

</table>

app/views/totos/new.html.erb
<h1 style="margin-left:40%;margin-top:5%;">create a new toto</h1><br><br>

<%= render 'form' %>

app/views/totos/show.html.erb
<h1>Showing a Todo</h1>

<p>
  name : <%= @toto.name %>
</p>
<p>
  description : <%= @toto.description %>
</p>
<p>
<%= link_to "Edit toto", edit_toto_path(@toto)%> |
<%= link_to "Back to Totos Listing", totos_path %>
</p>